export type Lang = "ar" | "fr" | "en";

export interface Translation {
  appName: string;
  appTagline: string;
  nav: { inventory: string; pos: string; reports: string; settings: string };
  scanner: { title: string; hint: string; permissionDenied: string };
  activation: { subtitle: string; step1: string; step2: string; scanHint: string; startScan: string; passwordPlaceholder: string; button: string; back: string; qrVerified: string; qrInvalid: string; success: string; invalid: string };
  inventory: { addProduct: string; editProduct: string; search: string; allCategories: string; sortName: string; sortPrice: string; sortQty: string; asc: string; desc: string; empty: string; emptyHint: string; noResults: string; lowStock: string; outOfStock: string; stats: { products: string; units: string; value: string; lowStock: string } };
  form: { save: string; cancel: string; delete: string; deleted: string; saved: string; required: string; name: string; category: string; color: string; size: string; quantity: string; purchasePrice: string; salePrice: string; lowStockThreshold: string; barcode: string; scan: string; generate: string; image: string; pickImage: string; changeImage: string; printBarcode: string; confirmDelete: string };
  pos: { title: string; search: string; notFound: string; cart: string; emptyCart: string; emptyHint: string; qty: string; price: string; lineTotal: string; subtotal: string; discount: string; total: string; paymentMethod: string; cash: string; card: string; other: string; customerName: string; pay: string; saleSuccess: string; stockWarning: string; invoice: string; invoiceNo: string; date: string; item: string; printInvoice: string; thanks: string };
  reports: { title: string; today: string; week: string; month: string; year: string; revenue: string; profit: string; salesCount: string; avgSale: string; topProducts: string; recentSales: string; units: string; noSales: string; chartSales: string };
  settings: { title: string; language: string; currency: string; exchangeRate: string; theme: string; themeLight: string; themeDark: string; store: string; storeName: string; storePhone: string; storeAddress: string; saved: string; backup: string; export: string; import: string; exported: string; imported: string; importError: string };
}

export const translations: Record<Lang, Translation> = {
  ar: {
    appName: "ClowtheX",
    appTagline: "إدارة محل الملابس",
    nav: { inventory: "المخزون", pos: "نقطة البيع", reports: "التقارير", settings: "الإعدادات" },
    scanner: { title: "مسح الباركود", hint: "وجّه الكاميرا نحو الباركود", permissionDenied: "لا يمكن الوصول إلى الكاميرا" },
    activation: { subtitle: "يرجى تفعيل التطبيق للمتابعة", step1: "امسح رمز QR للتفعيل", step2: "أدخل كلمة المرور", scanHint: "وجّه الكاميرا نحو رمز QR أعلاه", startScan: "بدء المسح", passwordPlaceholder: "كلمة المرور", button: "تفعيل", back: "رجوع", qrVerified: "تم التحقق من رمز QR", qrInvalid: "رمز QR غير صحيح", success: "تم تفعيل التطبيق بنجاح", invalid: "كلمة المرور غير صحيحة" },
    inventory: { addProduct: "إضافة منتج", editProduct: "تعديل المنتج", search: "بحث عن منتج...", allCategories: "جميع الفئات", sortName: "الاسم", sortPrice: "السعر", sortQty: "الكمية", asc: "تصاعدي", desc: "تنازلي", empty: "المخزون فارغ", emptyHint: "ابدأ بإضافة منتجاتك", noResults: "لا توجد نتائج", lowStock: "مخزون منخفض", outOfStock: "نفد المخزون", stats: { products: "منتجات", units: "وحدات", value: "القيمة", lowStock: "مخزون منخفض" } },
    form: { save: "حفظ", cancel: "إلغاء", delete: "حذف", deleted: "تم الحذف", saved: "تم الحفظ", required: "هذا الحقل مطلوب", name: "اسم المنتج", category: "الفئة", color: "اللون", size: "المقاس", quantity: "الكمية", purchasePrice: "سعر الشراء", salePrice: "سعر البيع", lowStockThreshold: "حد المخزون المنخفض", barcode: "الباركود", scan: "مسح", generate: "توليد", image: "الصورة", pickImage: "اختر صورة", changeImage: "تغيير الصورة", printBarcode: "طباعة الباركود", confirmDelete: "هل تريد حذف هذا المنتج؟" },
    pos: { title: "نقطة البيع", search: "ابحث عن منتج أو امسح الباركود...", notFound: "لم يتم العثور على المنتج", cart: "السلة", emptyCart: "السلة فارغة", emptyHint: "ابحث عن منتج لإضافته", qty: "الكمية", price: "السعر", lineTotal: "المجموع", subtotal: "المجموع الفرعي", discount: "الخصم", total: "الإجمالي", paymentMethod: "طريقة الدفع", cash: "نقداً", card: "بطاقة", other: "أخرى", customerName: "اسم العميل", pay: "إتمام البيع", saleSuccess: "تمت عملية البيع بنجاح", stockWarning: "الكمية تتجاوز المخزون", invoice: "فاتورة", invoiceNo: "رقم الفاتورة", date: "التاريخ", item: "المنتج", printInvoice: "طباعة الفاتورة", thanks: "شكراً لتسوقكم معنا" },
    reports: { title: "التقارير", today: "اليوم", week: "الأسبوع", month: "الشهر", year: "السنة", revenue: "الإيرادات", profit: "الربح", salesCount: "عدد المبيعات", avgSale: "متوسط البيع", topProducts: "أكثر المنتجات مبيعاً", recentSales: "آخر المبيعات", units: "وحدة", noSales: "لا توجد مبيعات", chartSales: "مبيعات" },
    settings: { title: "الإعدادات", language: "اللغة", currency: "العملة", exchangeRate: "سعر الصرف (1€ = د.ج)", theme: "المظهر", themeLight: "فاتح", themeDark: "داكن", store: "معلومات المتجر", storeName: "اسم المتجر", storePhone: "رقم الهاتف", storeAddress: "العنوان", saved: "تم حفظ الإعدادات", backup: "النسخ الاحتياطي", export: "تصدير البيانات", import: "استيراد البيانات", exported: "تم التصدير بنجاح", imported: "تم الاستيراد بنجاح", importError: "فشل الاستيراد" },
  },
  fr: {
    appName: "ClowtheX", appTagline: "Gestion de boutique",
    nav: { inventory: "Inventaire", pos: "Vente", reports: "Rapports", settings: "Paramètres" },
    scanner: { title: "Scanner", hint: "Pointez vers le code-barres", permissionDenied: "Caméra refusée" },
    activation: { subtitle: "Activez l'application", step1: "Scannez le QR code", step2: "Mot de passe", scanHint: "Pointez vers le QR code", startScan: "Scanner", passwordPlaceholder: "Mot de passe", button: "Activer", back: "Retour", qrVerified: "QR vérifié", qrInvalid: "QR invalide", success: "Activé", invalid: "Incorrect" },
    inventory: { addProduct: "Ajouter", editProduct: "Modifier", search: "Rechercher...", allCategories: "Toutes", sortName: "Nom", sortPrice: "Prix", sortQty: "Quantité", asc: "Croissant", desc: "Décroissant", empty: "Vide", emptyHint: "Ajoutez des produits", noResults: "Aucun résultat", lowStock: "Stock faible", outOfStock: "Rupture", stats: { products: "Produits", units: "Unités", value: "Valeur", lowStock: "Stock faible" } },
    form: { save: "Enregistrer", cancel: "Annuler", delete: "Supprimer", deleted: "Supprimé", saved: "Enregistré", required: "Obligatoire", name: "Nom", category: "Catégorie", color: "Couleur", size: "Taille", quantity: "Quantité", purchasePrice: "Prix achat", salePrice: "Prix vente", lowStockThreshold: "Seuil", barcode: "Code-barres", scan: "Scanner", generate: "Générer", image: "Image", pickImage: "Choisir", changeImage: "Changer", printBarcode: "Imprimer", confirmDelete: "Supprimer?" },
    pos: { title: "Vente", search: "Rechercher...", notFound: "Introuvable", cart: "Panier", emptyCart: "Vide", emptyHint: "Ajoutez un produit", qty: "Qté", price: "Prix", lineTotal: "Total", subtotal: "Sous-total", discount: "Remise", total: "Total", paymentMethod: "Paiement", cash: "Espèces", card: "Carte", other: "Autre", customerName: "Client", pay: "Valider", saleSuccess: "Vente effectuée", stockWarning: "Stock insuffisant", invoice: "Facture", invoiceNo: "N°", date: "Date", item: "Article", printInvoice: "Imprimer", thanks: "Merci" },
    reports: { title: "Rapports", today: "Aujourd'hui", week: "Semaine", month: "Mois", year: "Année", revenue: "CA", profit: "Bénéfice", salesCount: "Ventes", avgSale: "Moyenne", topProducts: "Top", recentSales: "Récentes", units: "u", noSales: "Aucune", chartSales: "Ventes" },
    settings: { title: "Paramètres", language: "Langue", currency: "Devise", exchangeRate: "Taux", theme: "Thème", themeLight: "Clair", themeDark: "Sombre", store: "Magasin", storeName: "Nom", storePhone: "Tél", storeAddress: "Adresse", saved: "Enregistré", backup: "Sauvegarde", export: "Exporter", import: "Importer", exported: "Exporté", imported: "Importé", importError: "Erreur" },
  },
  en: {
    appName: "ClowtheX", appTagline: "Clothing Store Manager",
    nav: { inventory: "Inventory", pos: "Point of Sale", reports: "Reports", settings: "Settings" },
    scanner: { title: "Scan Barcode", hint: "Point camera at barcode", permissionDenied: "Camera denied" },
    activation: { subtitle: "Please activate the app", step1: "Scan QR code", step2: "Enter password", scanHint: "Point camera at QR code", startScan: "Start Scan", passwordPlaceholder: "Password", button: "Activate", back: "Back", qrVerified: "QR verified", qrInvalid: "Invalid QR", success: "Activated", invalid: "Incorrect" },
    inventory: { addProduct: "Add Product", editProduct: "Edit Product", search: "Search...", allCategories: "All", sortName: "Name", sortPrice: "Price", sortQty: "Qty", asc: "Asc", desc: "Desc", empty: "Empty", emptyHint: "Add products", noResults: "No results", lowStock: "Low Stock", outOfStock: "Out of Stock", stats: { products: "Products", units: "Units", value: "Value", lowStock: "Low Stock" } },
    form: { save: "Save", cancel: "Cancel", delete: "Delete", deleted: "Deleted", saved: "Saved", required: "Required", name: "Name", category: "Category", color: "Color", size: "Size", quantity: "Quantity", purchasePrice: "Purchase Price", salePrice: "Sale Price", lowStockThreshold: "Low Stock", barcode: "Barcode", scan: "Scan", generate: "Generate", image: "Image", pickImage: "Pick", changeImage: "Change", printBarcode: "Print", confirmDelete: "Delete?" },
    pos: { title: "Point of Sale", search: "Search or scan...", notFound: "Not found", cart: "Cart", emptyCart: "Empty", emptyHint: "Add a product", qty: "Qty", price: "Price", lineTotal: "Total", subtotal: "Subtotal", discount: "Discount", total: "Total", paymentMethod: "Payment", cash: "Cash", card: "Card", other: "Other", customerName: "Customer", pay: "Pay", saleSuccess: "Sale done", stockWarning: "Low stock", invoice: "Invoice", invoiceNo: "No.", date: "Date", item: "Item", printInvoice: "Print", thanks: "Thank you" },
    reports: { title: "Reports", today: "Today", week: "Week", month: "Month", year: "Year", revenue: "Revenue", profit: "Profit", salesCount: "Sales", avgSale: "Average", topProducts: "Top", recentSales: "Recent", units: "u", noSales: "No sales", chartSales: "Sales" },
    settings: { title: "Settings", language: "Language", currency: "Currency", exchangeRate: "Rate", theme: "Theme", themeLight: "Light", themeDark: "Dark", store: "Store", storeName: "Name", storePhone: "Phone", storeAddress: "Address", saved: "Saved", backup: "Backup", export: "Export", import: "Import", exported: "Exported", imported: "Imported", importError: "Error" },
  },
};
